### ISSUE TITLE
Old code

### ISSUE THREAD

**Issue by sjamaan** [certainty/chicken_sendfile#1]
Hi David!

I was looking for the repo for sendfile, and only found this one. The hg one at bitbucket is gone.

When did you import this one? It doesn't seem to have the more recent code that adds CHICKEN 5 support?

**Comment by certainty** [comment]
Hi Peter,
I don't remember exactly but I'm relatively sure this was imported roughly around the time of the last commit. So 2014.
I saw that updates have been added to the egg and was under the impression the maintainer has changed. 

Vasilij Schneidermann wrote an E-Mail a while back with a PR against the bitbucket repository. He might have a clone still?

**Comment by sjamaan** [comment]
I still have a hg repo here, which has commits until 2018. So I guess there's quite a bit missing.  What's the best way to get this git repo up to date with that?

**Comment by certainty** [comment]
There is indeed quite something missing. The last tag here is 1.7.3 whereas the version history over on http://wiki.call-cc.org/eggref/5/sendfile mentions 1.8.3. 

> What's the best way to get this git repo up to date with that? 

One thing worth a try is using the procedure defined here: https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git and convert the mercurial repository to git and then create a PR. I'm happy to give you committer access to the repository (or any other chicken related repository, just in case). 

This would likely keep the history in tact. Likely the git tags would have to be set by hand after the PR has been merged.

**Comment by sjamaan** [comment]
I got a [git repo now](https://github.com/sjamaan/sendfile) but there's no shared ancestry, so I can't make a PR for it.

Rebasing doesn't work either for the same reason.

Maybe you can do a few basic checks with my repo to make sure it's okay and nuke this repo and then import mine under here?

**Comment by certainty** [comment]
@sjamaan Alright, I've created a PR with the changes here: https://github.com/certainty/chicken_sendfile/pull/2 

Before I merge I'd like to make sure that the code builds and tests. Once it's merged I can restore the tags and we should be good. I won't be able to do this today though. 

I've already send you an invite to become a collaborator on this repository in case you want to move ahead already.

**Comment by wasamasa** [comment]
I have obtained a fork as well. It has four more commits than Peter's: https://github.com/wasamasa/sendfile/tree/master

**Comment by certainty** [comment]
@wasamasa would you be willing to take ownership of this and maintain it? 

In that case the way forward would probably be to update repository information in the coop (and the release-Info)

**Comment by wasamasa** [comment]
Yes, I would. Not sure where I'd keep it though, as I don't want to rely on GitHub if I can avoid it.

**Comment by certainty** [comment]
Ok. @sjamaan what would be the way to move the canonical repository for this egg? If I recall right there was some meta info which would needs to be updated.

**Comment by sjamaan** [comment]
The `release-info` file needs to be updated, as well as the master egg list in svn (which is currently disabled because the bitbucket repo disappeared)

**Comment by certainty** [comment]
Ok let’s decouple the maintenance question for now and get the egg enabled again. I‘ll cherry pick the changes and update the release-info, so there is a repository that’s reachable. Then we can figure out where to host the repos ultimately.

**Comment by certainty** [comment]
@sjamaan @wasamasa I've merged the new code to master and also updated the release info.
The following versions are known:
```
$ chicken-install -list-versions sendfile                                                                                                                                       
sendfile: 1.8.1 1.8.0 1.8.2 1.8.3
```

I've tried to build the tags by running the following for each of those versions
```
chicken-install -test sendfile:1.8.x
```

All of those were built and test successfully.

Could you please give it a try on your systems?

**Comment by wasamasa** [comment]
I can install all those versions successfully.

**Comment by certainty** [comment]
@sjamaan would you please update the master egg list?

**Comment by sjamaan** [comment]
Done!

**Comment by certainty** [comment]
Alight, thanks. I tried to install the egg on a different machine (version 1.8.3) and it worked. 
I'm going to close this issue.
